### PR TITLE
ci: Ubuntu updates

### LINKED ISSUE #1928: Ubuntu CI on latest revision is not working
**Describe the bug**
> A clear and concise description of what the bug is.
As per discussion on slack:
Investigate as to why `ubuntu-latest` is failing dramatically on the CI.

github token secret was not properly decoded or missing
some unit tests were failing 

**To Reproduce**
> Steps to reproduce the behavior:

Check all the changes relating to CI and ubuntu-latest. For now ubuntu-18.04 is only working version.
https://github.com/Flank/flank/pull/1927
https://github.com/Flank/flank/pull/1918

**Expected behavior**
> A clear and concise description of what you expected to happen.

ubuntu-latest works.

### PR DESCRIPTION
**Pull request by Sloox**
Fixes #1928 

Revert to latest, ubuntu-latest and include fixes.

## Checklist
- [ ] Integration tests updated

### CODE REVIEW

**Comment by Sloox** [comment]
@flank-it

**Comment by Sloox** [comment]
@pawelpasterz not sure if anything changed. But its all passing. Had issues on my fork but they dissapeared. 
Maybe it needs to be merged before changes are sseen? 
WDYT?

**Comment by pawelpasterz** [comment]
> @pawelpasterz not sure if anything changed. But its all passing. Had issues on my fork but they dissapeared.
> Maybe it needs to be merged before changes are sseen?
> WDYT?

Yeah, changes in workflow are applied once merged to master. Let's give it a try.

One question, there are two ubuntu versions used `latest` and `20.04`, shouldn't we use one of them?

**Comment by piotradamczyk5** [comment]
> > @pawelpasterz not sure if anything changed. But its all passing. Had issues on my fork but they dissapeared.
> > Maybe it needs to be merged before changes are sseen?
> > WDYT?
> 
> Yeah, changes in workflow are applied once merged to master. Let's give it a try.
> 
> One question, there are two ubuntu versions used `latest` and `20.04`, shouldn't we use one of them?

`ubuntu-latest` is `ubuntu-20.04` so for now there is not difference 😄  lets stick to `ubuntu-latest`

**Review by piotradamczyk5 — APPROVED** [review]

**Review by adamfilipow92 — APPROVED** [review]

**Review by Sloox — COMMENTED** [review]
Testing

**Comment by Sloox** [comment]
@flank-it

**Pull request merged**
