### PR TITLE
ci: Windows integration test

### LINKED ISSUE #1527: Re-introduce integration tests for windows
**Author the user story for this feature**

I would like to ensure Windows as a platform is supported.
Integration tests need to run successfully on a windows platform

**Describe the solution**
@flank-it should run a successful windows instance.

### PR DESCRIPTION
**Pull request by Sloox**
Fixes #1527 

Run @flank-it to see if it passes succesfully
.

## Checklist
- [ ] Integration tests updated

### CODE REVIEW

**Comment by Sloox** [comment]
@flank-it

**Comment by Sloox** [comment]
@flank-it

**Comment by Sloox** [comment]
@flank-it

**Comment by Sloox** [comment]
@piotradamczyk5 and I discussed that it needs to merged in to actually confirm that it works successfully

**Review by piotradamczyk5 — APPROVED** [review]

**Review by adamfilipow92 — APPROVED** [review]
👍

**Pull request merged**
