### PR TITLE
test: Update compare file and make url option not required

### LINKED ISSUE #1508: IT are flaky
There are inconsistent IT results. Sometimes IT fails on CI but after rerun, they pass without any significant improvements or changes. I think `Uploading (...)` sometimes does not start from the new line and IT regex can't handle it. Check [THOSE](https://scans.gradle.com/s/h5iodu5erzm7c/tests/:integration_tests:integrationTests/integration.MultipleApksIT/flank%20full%20option%20run#1) results: 
```
Saved 3 shards to android_shards.json
 Uploading [android_shards.json] to https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-01-18_05-46-54.996000_UnjS/... |  
 Uploading [app-debug.apk] to https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-01-18_05-46-54.996000_UnjS/... |  
 Uploading [MainActivity_robo_script.json] to https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-01-18_05-46-54.996000_UnjS/..  Uploading [app-multiple-success-debug-androidTest.apk] to https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-01-18_05-46-54.996000_UnjS/.... |  
 Uploading [app-multiple-error-debug-androidTest.apk] to https://console.developers.google.com/storage/browser/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2021-01-18_05-46-54.996000_UnjS/...

```
But this is my guess and failure should be investigated more deeply.

Another case is missing build scan URL which is unexpectedly (again, sometimes) missing which causes the workflow to fail (with error `Missing option --github-token` which can be misleading). The cause is not related to flank (as far as I was able to verify at least).
https://github.com/Flank/flank/runs/1718735076?check_suite_focus=true
Screenshot 2021-01-18 at 07 34 10

----

#### TODO list
1. Fix uploading section verification, possible solutions:
    1. make regex able to handle `Uploading (...)`  NOT started from the new line
    2. do not upload asynchronously, this is an easy win. Maybe artifacts are not so big and uploading them synchronously does not have a huge impact on the overall flank run time?
    3. (is there something more to fix? -- `Uploading (...)` section did not cause IT to fail)
1. Prevent workflow to fail on missing `--url`
    1. make `--url` not required or with default value
    2. add logic to inform user if there is URL missing (instead of URL we can print `Not accessible` in the issue comment)
   
#### DoD
Since it's hard to reproduce it will be also hard to verify correct implementation. Let's try to have all cases covered with UT in the best way we can.

### PR DESCRIPTION
**Pull request by pawelpasterz**
Fixes #1508 

Removes unnecessary regex in multiple apk compare file. Make process result command resistant for missing `--url` option

1. `./gradlew build`
2. All tests pass
3. Run 
    ```
    java -jar ./flank-scripts/build/libs/flank-scripts.jar integration processResults \
      --result=failure \
      --url=  \
      --github-token=[actually can be anything] \
      --run-id=123456
    ```
4. Observe output in console contains:
    ```
    ** Parameters:
     result: FAILURE
     url:    No build scan URL provided
     runID:  123456
    ```
5. You can also verify if a comment is posted properly. To do it, update your `flank-debug.properties` with your repo and run 3) with the correct gh token.
6. In the newly created issue `No build scan URL provided` should be present in a comment

## Checklist

- [x] Unit tested
- [x] Integration tests updated

### CODE REVIEW

**Comment by pawelpasterz** [comment]
@flank-it

**Review by piotradamczyk5 — APPROVED** [review]

**Review by piotradamczyk5 — APPROVED** [review]

**Comment by pawelpasterz** [comment]
@flank-it

**Comment by pawelpasterz** [comment]
Should be retested and merged after https://github.com/Flank/flank/pull/1521

**Comment by piotradamczyk5** [comment]
@flank-it

**Comment by pawelpasterz** [comment]
IT failing due to quota limit exceeded...

**Comment by pawelpasterz** [comment]
@flank-it

**Comment by jan-gogo** [comment]
I have run flank-it once more. If the PR is fixing IT flakiness the tests should pass at least twice in a row.

**Review by adamfilipow92 — APPROVED** [review]
- [X] Looks good
- [X] Integration tests works

**Pull request merged**
