### PR TITLE
test: Add IT for large shard test suite

### LINKED ISSUE #1650: Add IT for #1649
This is a follow-up issue.

We should implement IT that will cover case fixed in https://github.com/Flank/flank/pull/1649

IT should cover:
* test run where at least one shard has more than 50 tests
* since this is an issue related to test result API usage android test should be enough (iOS uses legacy, XML based approach)

### PR DESCRIPTION
**Pull request by piotradamczyk5**
Fixes #1650

New IT succeed.

## Checklist

- [x] Integration tests updated

### CODE REVIEW

**Comment by piotradamczyk5** [comment]
@flank-it

**Comment by piotradamczyk5** [comment]
> **Integration tests failed ❌**
> Windows status failure - Build scan:
> MacOS status failure - Build scan: https://gradle.com/s/e7667dkfyecno
> Linux status failure - Build scan: https://gradle.com/s/webnikda6mhwe
> Workflow run https://github.com/Flank/flank/actions/runs/687256988

quota limit...

**Review by adamfilipow92 — APPROVED** [review]
- [X] code looks good
- [X] on local machine, test passed

**Comment by adamfilipow92** [comment]
@flank-it

**Review by Sloox — APPROVED** [review]

**Comment by pawelpasterz** [comment]
@flank-it

**Pull request merged**
