### PR TITLE
fix: Add storage dir support

### LINKED ISSUE #1873: Flank fails on valid `directories-to-pull` inputs, /storage dirs not supported
The [gcloud docs](https://cloud.google.com/sdk/gcloud/reference/alpha/firebase/test/android/run#--directories-to-pull) state that `/storage` sudirectories can be pulled from test devices. Flank [does not yet support](https://github.com/Flank/flank/blob/e4c9e25663a237982935c86ef95d94bdb3380a59/test_runner/src/main/kotlin/ftl/args/ValidateAndroidArgs.kt#L127) this. Adding support for `/storage` sudirectories is important for testing on API 30+ devices.

**To Reproduce**
1. Specify a `/storage` sudir in your flank config for `directories-to-pull`
2. Attempt to run Flank with your updated config

Example `directories-to-pull` section of config:
```yaml
directories-to-pull:
  - /sdcard/data/sample
  - /data/local/tmp/sample
  - /sdcard/
  - /storage
  - /storage/emulated/0/Download
```

**Expected behavior**
1. Adding `/storage` subdirs in a flank config does not error and results in those directories being pulled from test devices into gcloud buckets.

**Details (please complete the following information):**
> Have you tested on the latest Flank snapshot?
Yes
> Post the output of ` flank --version`.
version: v21.02.0

**Additional context**
> Add any other context about the problem here.
This is necessary because API 30+ restricts access to external storage, meaning `/sdcard` directories are not available for pulling important test data on API 30+ devices. One workaround is storing that data in the downloads folder (typically `/storage/emulated/0/Download` on an emulator). As more teams move to update their test devices in FTL to API 30+, this will become more and more important to support.

### PR DESCRIPTION
**Pull request by wclausen**
Fixes #1873 

## Test Plan
Updated the tests in `ValidateDirectoriesToPullAndroidArgsTest` to include changes in this PR

## Checklist

- [x] Documented
- [x] Unit tested

### CODE REVIEW

**Comment by pawelpasterz** [comment]
Thanks for PR!
LGTM, just sign CLA and we're good to go :)

**Review by jan-gogo — APPROVED** [review]

**Review by piotradamczyk5 — APPROVED** [review]

**Comment by wclausen** [comment]
@pawelpasterz great! I wrote this as part of my work at Dropbox and had to get the legal team to sign off on me signing the CLA. I don't anticipate an issue and will sign as soon as I get the go-ahead.

**Review by Sloox — APPROVED** [review]
👍

**Comment by Sloox** [comment]
@wclausen if you run into any issue with the CLA and cannot sign for any reason. Let us know and we will implement the changes for you. You are welcome to ping anyone who has reviewed this and we will gladly do it for you. 😄

**Comment by wclausen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
