### PR TITLE
refactor: Clean up dependencies

### PR DESCRIPTION
**Pull request by pawelpasterz**
PR removes a couple of unused dependencies

Both build and IT run finish without any error

### CODE REVIEW

**Comment by pawelpasterz** [comment]
@flank-it

**Review by Sloox — CHANGES_REQUESTED** [review]
Are we sure of these changes I somehow think some of them like:
api(Dependencies.Fuel.KOTLINX_SERIALIZATION)
are needed?

**Comment by Sloox** [comment]
Ahh i see they are succeeding :)

**Comment by pawelpasterz** [comment]
Work is still in progress, there might be some changes as I'm experimenting a bit 😅

**Comment by pawelpasterz** [comment]
@flank-it

**Review by Sloox — APPROVED** [review]
Always good to remove dependencies, can speed things up. Lets just hope we don't need them later.

**Review by piotradamczyk5 — APPROVED** [review]

**Pull request merged**
