### PR TITLE
refactor: Refactor flank scripts

### LINKED ISSUE #1356: Refactor flank-scripts [PROPOSAL]
**User story**

As a developer, I want to have well-structured and described flank-scripts commands so I can clearly understand the purpose of each, also maintain and scale the module without a doubt.

**Description of the problem**
1. The packages structure is designed in a semi-random manner, which makes to code harder to scale and may cause additional inconsequences in the future.
1. The CLI that uses thirty part libraries is bounded with domain and occasionally contains logical operations that break SRP and separation of concerns.
1. The command hierarchy is not well structured and described.

**Requirements**
1. According to the separation of concerns principle, the logical part of the code should be separated from others. 
1. The CLI layer that uses third-party libraries (CliKt) should be thin as possible and free of logical operations for increasing code portability.
1. The domain layer should be designed a flat as possible manner. Each feature should be exposed as a single pure function separated from others, that operates on a utility code.
1. Only non-domain code should be reusable so it's important to design a common package carefully.
1. Each command must have a description that explains the purpose of the command and the possible result of the call.

**Proposed solution**

There are 3 important layers (packages) for `flank-scripts` module:
1. `cli`. Thin non-logical layer, a glue between program arguments and domain logic. Also specifies command-line documentation.
2. `ops`. The domain layer contains logical operations. Should be clean, easy to understand, and straightforward.
3. `util`. A non-domain reusable layer that contains utility code. The API should be simple and declarative.

Working steps:
1. Separate logical operations from CliKt commands.
1. Design a new structure for commands.
1. Group CliKt commands in `cli` package and fix the structure 
1. Fix descriptions of commands.
1. Separate common layer
1. Refactor common layer API
1. Group all domain code in `ops` package (ops as shorthand for operations) 
1. Refactor and restructure `ops` package
1. Use a standardized naming convention for commands (camel-case preferred as easier to write).

### LINKED ISSUE #1541: Organize flank scripts into separated layers
**Author the user story for this feature**

As a contributor, I want to have layers grouped in packages so I can easily identify the responsibility of each.

**Describe the solution**
1. Separate logical operations from CliKt commands.
1. Group CliKt commands in `cli` package and fix the structure
1. Group all domain code in `ops` package
1. Separate `utils` and `data`

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1541

All tests pass, Flank scripts work like before

## Checklist

- [X] CiCommand
- [X] ContributionCommand
- [X] DependenciesCommand
- [X] PullRequestCommand
- [x] IntegrationCommand 
- [x] ReleaseCommand
- [x] ShellCommand 
   - [x]   FirebaseCommand, 
   - [x]   BuildExampleCommand, 
   - [x]   BuildFtlCommand,
   - [x]   RunFtlLocalCommand,
   - [x]   UniversalFrameworkCommand,
   - [x]   OpsCommand,
   - [x]   UpdateBinariesCommand,
   - [x]   BuildFlankCommand,
   - [x]   InstallXcPrettyCommand,
   - [x]   SetupIosEnvCommand
- [x] TestArtifactsCommand
- [x] Utils
- [x] Tests

### CODE REVIEW

**Comment by axelzuziak-gogo** [comment]
Converted to #1406

**Comment by axelzuziak-gogo** [comment]
This PR is implementation of a #1541

**Comment by axelzuziak-gogo** [comment]
Comment for a future: Maybe we can this kind of PR's extract into smaller batches. For example this issue could be solved in 4 different PRs:
1. Separate logical operations from CliKt commands.
2. Group CliKt commands in cli package and fix the structure
3. Group all domain code in ops package
4. Separate utils and data

What do you think?

Nvm, I'm reviewing it 😃

**Review by jan-gogo — APPROVED** [review]

**Comment by jan-gogo** [comment]
> Comment for a future: Maybe we can this kind of PR's extract into smaller batches. For example this issue could be solved in 4 different PRs:

IMO it's not necessary, there is a lot of changes but only about moving the code between packages.

**Review by axelzuziak-gogo — APPROVED** [review]

**Pull request merged**
