### PR TITLE
Fix overlapping results

### LINKED ISSUE #792: Test results from shards with overlapping names in different matrices are lost
_The below is a speculation based on the data I've been able to collect and interpret so far._

I'm trying to upgrade a fairly sized multi-module project to the latest flank version (via fladle) with minimal config changes but so far I'm unsuccessful at that, not sure if I'm doing something wrong.

The fladle plugin is applied to the top-level `build.gradle` and extra test apk's from the submodules are pulled in with `additionalTestApks`. After all the tests are run, we download sdcard contents of all shards from the returned combined test bucket. Specifically in our case, we are interested in `coverage.ec` files from all the sdcard, which we merge together with the help of the jacoco gradle plugin.

After upgrade to the new flank version, the coverage dropped suddenly and significantly. What I think is happening is files from different gradle modules are overwriting each other in the combined results bucket. So for instance for `:module1` 3 shards are created and collected in `Pixel2-29-en-portrait-shard_0/`, `Pixel2-29-en-portrait-shard_1/`, `Pixel2-29-en-portrait-shard_2/` directories in the combined bucket. Then say :module2 is large enough to have 2 shards created for its tests: `Pixel2-29-en-portrait-shard_0/`, `Pixel2-29-en-portrait-shard_1/`. All the directories with the overlapping names get copied over to the same bucket and the last one wins, so the coverage execution data from the "losing" shards is lost. There's also a new `Pixel2-29-en-portrait-test_results_merged.xml` file in the results bucket, which also doesn't contain all tests being run which confirms my suspicion that there are multiple `Pixel2-29-en-portrait-test_results_merged.xml` files coming from different matrices and this is just one survivor of them.

### PR DESCRIPTION
**Pull request by pawelpasterz**
# This PR will break backward compatibility due to different directory structure for both gcs and local results, but is essential to fix overlapping results bug

Fixes #792 

Add matrix level to directory tree structure for gcs . iOS structure remains the same.
Within this change local dir structure will be exactly the same as gcs'. 
**iOS path should be inlined with android once FTL introduces server side sharding for iOS.**

#### Examples:
Android:
- gcs -> `test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-05-21_07-57-00.760000_AIxU/matrix_2/NexusLowRes-28-en-portrait-shard_0`
- local -> `results/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-05-21_07-57-00.760000_AIxU/matrix_2/NexusLowRes-28-en-portrait-shard_0`

iOS:
- gcs -> `test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-05-21_08-38-22.460000_OnCd/shard_0/iphone8-11.2-en_US-portrait/`
- local -> `results/test-lab-v9cn46bb990nx-kz69ymd4nm9aq/2020-05-21_08-38-22.460000_OnCd/shard_0/iphone8-11.2-en_US-portrait/`

## Checklist

- [x] Unit tested
- [x] release_notes.md updated

### CODE REVIEW

**Comment by bootstraponline** [comment]
this looks good to me

**Comment by jan-gogo** [comment]
Pls update release notes :)

**Comment by pawelpasterz** [comment]
> Pls update release notes :)

Sure, it's just draft for the moment :)

**Comment by pawelpasterz** [comment]
@bootstraponline @jan-gogo 
Please take a look, I made some changes (please see description)
Thanks!

**Pull request merged**
