### PR TITLE
feat: Part 1 of multiple OS IT tests

### LINKED ISSUE #1553: Modify Integration processResult to handle 3 URLs & 3 results
processResult needs to be modified once the 3 urls have been passed to the correct locations. We also need to handle the 3 results correctly at this point.

### PR DESCRIPTION
**Pull request by Sloox**
Fixes #1553 

## Checklist
- [x] Integration tests updated

### CODE REVIEW

**Comment by Sloox** [comment]
actual modification of flankscripts will come next.

**Comment by Sloox** [comment]
@flank-it

**Review by adamfilipow92 — APPROVED** [review]
Cannot test but looks good 👍

**Review by piotradamczyk5 — APPROVED** [review]
Nice work!

**Pull request merged**
