### PR TITLE
feat: Parse corellium logs

### LINKED ISSUE #1800: Parsing Corellium output (logs)
* Implement parser for `am instrument -r -w` command logs
* The input should be the flow of console log lines.
* The output should be the flow of structured results.
* Deliver it as a library module.

### PR DESCRIPTION
**Pull request by pawelpasterz**
Fixes #1800

.

## Checklist

- [ ] Documented
- [ ] Unit tested
- [ ] Integration tests updated

### CODE REVIEW

**Comment by bootstraponline** [comment]
I found this article interesting. This gets us pragmatic access to adb.

- https://malinskiy.medium.com/adam-a-second-birth-to-androids-ddmlib-c90fdde4c39d 
- https://github.com/Malinskiy/adam

**Comment by pawelpasterz** [comment]
> I found this article interesting. This gets us programmatic access to adb.
> 
> * https://malinskiy.medium.com/adam-a-second-birth-to-androids-ddmlib-c90fdde4c39d
> * https://github.com/Malinskiy/adam
> * https://github.com/Malinskiy/adam/blob/master/docs/_docs/instrumentation/test-runner.md
> * https://github.com/Malinskiy/adam/blob/master/src/main/kotlin/com/malinskiy/adam/request/testrunner/transform/InstrumentationResponseTransformer.kt

Nice, will look into it

**Comment by pawelpasterz** [comment]
Not sure if we could use it in no-vpn approach. But log parser seems reasonable!

**Comment by bootstraponline** [comment]
> Not sure if we could use it in no-vpn approach. But log parser seems reasonable!

I'll check on the timeline for dropping the VPN. On iOS it'll be required, however there are plans to remove the VPN on Android.

**Comment by pawelpasterz** [comment]
> > Not sure if we could use it in no-vpn approach. But log parser seems reasonable!
> 
> I'll check on the timeline for dropping the VPN. On iOS it'll be required, however there are plans to remove the VPN on Android.

Would be awesome <3

**Pull request closed without merging**
