### PR TITLE
refactor: Flank scripts features not depends on each other

### LINKED ISSUE #1543: Make flank-scripts features not depends on each other
**Author the user story for this feature**

As a contributor, I want to keep features not dependent on each other so I don't have to be afraid of the hidden complexity of the domain layer.

**Describe the solution**

1. Identify relations between different `flank-scripts` features.
1. Consider identified code as a standalone utility(ies).
1. Move common implementation to the separated package(s) outside `ops`.

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1543 

The tests should pass. Scripts should work as before.

## Checklist

- [X] Unit tested

### CODE REVIEW

**Review by Sloox — CHANGES_REQUESTED** [review]
Is this only a package name change?

**Comment by adamfilipow92** [comment]
> Is this only a package name change?

I was moving some functions to ```common``` package like ```AppendReleaseNotes.kt``` because is used in two other packages.

**Review by piotradamczyk5 — APPROVED** [review]
It needs some adjustments after merge #1574 , but for now the main goal is achieved 👍

**Review by Sloox — APPROVED** [review]
Understand it now and approved: 🚀

**Pull request merged**
