### PR TITLE
fix: Update compare files in IT

### PR DESCRIPTION
**Pull request by pawelpasterz**
Fixes #1628 

1. Integration tests pass

### CODE REVIEW

**Comment by pawelpasterz** [comment]
@flank-it

**Comment by pawelpasterz** [comment]
Tests fail due to quota limit exceeded 🙄 But those which do not require actual test run, pass https://scans.gradle.com/s/c2y6c66zrnd3a/tests

**Review by Sloox — APPROVED** [review]
My bad. Didnt realize it would have an effect.

**Comment by pawelpasterz** [comment]
@flank-it

**Comment by Sloox** [comment]
@flank-it

**Comment by pawelpasterz** [comment]
Missing URL for windows is a known issue https://github.com/eskatos/gradle-command-action/issues/30

**Review by piotradamczyk5 — APPROVED** [review]

**Pull request merged**
