### PR TITLE
Update gradle to 6.2.1

### PR DESCRIPTION
**Pull request by doodla**
I had to modify the Jacoco config to work with the new version of gradle. For some reason, it was [crashing](https://github.com/Flank/flank/runs/466602241) with the previous config.

I also updated the Jacoco tool version to the latest ( 0.8.5 )

### CODE REVIEW

**Comment by doodla** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by doodla** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by doodla** [comment]
recheckcla

**Comment by pawelpasterz** [comment]
Hey @doodla could you change commits message to be more explanatory? Thanks :)

**Comment by doodla** [comment]
> Hey @doodla could you change commits message to be more explanatory? Thanks :)

I responded a similar comment [here](https://github.com/Flank/flank/pull/641#issuecomment-591103767) if anyone else cares.

**Comment by bootstraponline** [comment]
Thanks for contributing!

**Pull request merged**
