### PR TITLE
feat: Use Firebase Test Lab matrix details URL for test matrix webLink

### PR DESCRIPTION
**Pull request by tonybaroneee**
Hey all, Anthony from the Firebase Test Lab team here!

Here's a small PR to update the test matrix webLink to point to the new test matrix details page, which shows all test results listed by test case. We heard from users that they like this new view, as it shows a more holistic picture of all test executions. Let me know what you think. Thanks!

Here's a screenshot of the new page:

image

## Checklist

- [ ] Documented
- [X] Unit tested
- [X] Integration tests updated

### CODE REVIEW

**Comment by tonybaroneee** [comment]
recheck

**Comment by bootstraponline** [comment]
Thank you for the pull request! I sent you an invite to the Flank team and triggered the CI jobs. The code looks great. Once the CI jobs are green, I think this is good to merge.

**Review by bootstraponline — APPROVED** [review]

**Comment by tonybaroneee** [comment]
Much appreciated, thanks for the quick turnaround on this! Looking forward to future collab opportunities!

**Comment by bootstraponline** [comment]
CI is ✅. Merged!

**Comment by tonybaroneee** [comment]
@bootstraponline Great to hear, thanks!

**Pull request merged**
