### PR TITLE
Shard calculation should not use skipped tests time

### PR DESCRIPTION
**Pull request by kozaxinan**
Fixes https://github.com/Flank/flank/issues/2354

Added a new unit test to cover edge case. 

Smart flank should not use skipped tests time during the calculation of shard times.

## Checklist

- [ ] Documented
- [x] Unit tested
- [ ] Integration tests updated

### CODE REVIEW

**Comment by adamvduke** [comment]
@flank-it

**Comment by Fry-kun** [comment]
@flank-it

**Review by Fry-kun — APPROVED** [review]

**Comment by kozaxinan** [comment]
Hi, post job fails because of permission issues (i could be wrong)
Is there anything I should add to this PR? Is it ready to be merged?
Thank you for your support.

**Comment by kozaxinan** [comment]
Hi, post job fails because of permission issues (i could be wrong)
Is there anything I should add to this PR? Is it ready to be merged?
Thank you for your support.

**Comment by Fry-kun** [comment]
Yes, the `publish-scan-url` permission error is apparently expected for all external contributors. Should be OK to merge :+1:

**Comment by kozaxinan** [comment]
I don't have permission to merge as well. 🤣

**Pull request merged**
