### PR TITLE
feat: Add Flank version info to requests

### LINKED ISSUE #1925: Add Flank version info to client_info in the request
Version info can be added to the client_info field in the request. For instance, gcloud adds

```python
  name: "gcloud",
  client_info_details: [{
    key: "Cloud SDK Version",
    value: "340.0.0"
  },{
    key: "Release Track",
    value: "GA"
  }]
```

### PR DESCRIPTION
**Pull request by adamfilipow92**
Fixes #1925 

In user agent Flank, sends version and revision.

This change adds version and revision to user agent by ```setApplicationName``` method. Let me know if it's fine. We can also add a new header ```client_info``` by using ```setTestingRequestInitializer``` and ```setToolResultsRequestInitializer```.

### CODE REVIEW

**Review by bootstraponline — CHANGES_REQUESTED** [review]
ah, this isn't the right approach.

application name should stay the same. otherwise google is unable to pull stats on the flank client.

version info should be sent using client info details (as mentioned on the ticket)

**Comment by adamfilipow92** [comment]
> ah, this isn't the right approach.
> 
> application name should stay the same. otherwise google is unable to pull stats on the flank client.
> 
> version info should be sent using client info details (as mentioned on the ticket)

Thanks for the feedback, here is a current ```client_info``` example:

```

   "name":"Flank",
   "client_info_details":[
      {
         "key":"Flank Version",
         "value":"local_snapshot"
      },
      {
         "key":"Flank Revision",
         "value":"97854618886695c5005f9bc8d4e9a69eb7e922ed"
      }
   ]

```

I hope now everything is fine.

**Review by bootstraponline — APPROVED** [review]
this looks good to me!

let's have one other member of the team approve as well.

**Review by bootstraponline — CHANGES_REQUESTED** [review]
```python
return self._messages.TestMatrix(
        testSpecification=spec,
        environmentMatrix=environment_matrix,
        clientInfo=client_info,
        resultStorage=results,
        flakyTestAttempts=self._args.num_flaky_test_attempts or 0)
```
https://github.com/Flank/gcloud_cli/blob/55ba35ba9d631096f05f3c0bfa5cf1182134b47e/google-cloud-sdk/lib/googlecloudsdk/api_lib/firebase/test/ios/matrix_creator.py#L177

https://github.com/Flank/gcloud_cli/blob/55ba35ba9d631096f05f3c0bfa5cf1182134b47e/google-cloud-sdk/lib/googlecloudsdk/api_lib/firebase/test/matrix_creator_common.py#L25

I looked at the code in gcloud and we're suppose to set clientInfo on the TestMatrix object, not via a testing request initializer.

image

**Comment by adamfilipow92** [comment]
> ```python
> ```python
> return self._messages.TestMatrix(
>         testSpecification=spec,
>         environmentMatrix=environment_matrix,
>         clientInfo=client_info,
>         resultStorage=results,
>         flakyTestAttempts=self._args.num_flaky_test_attempts or 0)
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> https://github.com/Flank/gcloud_cli/blob/55ba35ba9d631096f05f3c0bfa5cf1182134b47e/google-cloud-sdk/lib/googlecloudsdk/api_lib/firebase/test/ios/matrix_creator.py#L177
> https://github.com/Flank/gcloud_cli/blob/55ba35ba9d631096f05f3c0bfa5cf1182134b47e/google-cloud-sdk/lib/googlecloudsdk/api_lib/firebase/test/matrix_creator_common.py#L25
> I looked at the code in gcloud and we're suppose to set clientInfo on the TestMatrix object, not via a testing request initializer.
> ```

Right, thanks! I changed my implementation to using client info on the TestMatrix.

**Review by Sloox — APPROVED** [review]

**Review by piotradamczyk5 — APPROVED** [review]

**Review by bootstraponline — APPROVED** [review]

**Pull request merged**
