### PR TITLE
feat: Add support for emulator devices

### PR DESCRIPTION
**Pull request by pawelpasterz**
In the scope of #1710

PR adds support for `EMULATOR` devices

1. build flank locally with `./gradlew flankFullRun`
2. ensure you are logged to `flank-open-source` project
3. run `flank firebase test android models list`
4. you should see new devices of type `EMULATOR`
5. run a simple test with
    ```
      device:
         - model: NexusLowResEmulator
           version: 28
    ```
6. tests should finish normally

## Checklist

- [x] Unit tested

### CODE REVIEW

**Comment by pawelpasterz** [comment]
@flank-it

**Comment by inktomi** [comment]
How will this work with the existing checks for max shards? They check specifically physical and virtual devices - as best I know there are not limits for these new emulators - so we should ensure that they don't fall into a default bucket of some sort in the validation logic.

**Comment by pawelpasterz** [comment]
> How will this work with the existing checks for max shards? They check specifically physical and virtual devices - as best I know there are not limits for these new emulators - so we should ensure that they don't fall into a default bucket of some sort in the validation logic.

We will introduce skipping validation option in a future PR. AFAIK emulators are considered as virtual devices so you can use up to 500 shards. Just wanted to keep PR scope related to one topic :)

**Review by Sloox — APPROVED** [review]
10k lines made me cry at first

**Review by piotradamczyk5 — APPROVED** [review]

**Pull request merged**
