### PR TITLE
fix: Uploading performance metrics for multiple matrices

### LINKED ISSUE #1322: Performance metrics for num-test-runs
**Author the user story for this feature**

As a user, I want to see performance metrics for each run so I can understand performance.

**Describe the solution**

> in the testing I’m doing I’m running flank on 2 tests setting the num-test-runs property to 10.. and after going through the results (which for this particular scenario are 10 matrices with 2 shards each), I noticed that the perf metrics file was only uploaded for one of them which is a bit odd
>
> https://firebase-community.slack.com/archives/C72V6UW8M/p1605306047111800?thread_ts=1603928728.053400&cid=C72V6UW8M

### PR DESCRIPTION
**Pull request by piotradamczyk5**
Fixes #1322 

1. Run flank on Android physical device. For example with configuration entry:
```yaml
gcloud:
...
  device:
    - model: OnePlus6T
      version: 28
...
```
2. Run Flank with multiple matrices. Example with using option
```yaml
...
flank:
  num-test-runs: 2
...
```

3. Check that `performanceMetrics.json` is uploaded for each matrix

## Checklist

- [x] Unit tested

### CODE REVIEW

**Review by pawelpasterz — CHANGES_REQUESTED** [review]
https://github.com/Flank/flank/pull/1329/checks?check_run_id=1414353358

**Review by Sloox — APPROVED** [review]
Fix the tests and we all good!

**Comment by adamfilipow92** [comment]
> https://github.com/Flank/flank/pull/1329/checks?check_run_id=1414353358

Tests fixed

**Comment by pawelpasterz** [comment]
I followed the test plan but can't find any `performanceMetrics.json`
Here is my config
```
gcloud:
  app: /Users/gogo/testowy_pawel/app-debug.apk
  test: /Users/gogo/testowy_pawel/app-single-success-debug-androidTest.apk
flank:
    num-test-runs: 3
    output-style: single
```

Let me know if I am doing something wrong

**Comment by piotradamczyk5** [comment]
> I followed the test plan but can't find any `performanceMetrics.json`
> Here is my config
> 
> ```
> gcloud:
>   app: ~/app-debug.apk
>   test: ~/app-single-success-debug-androidTest.apk
> flank:
>     num-test-runs: 3
>     output-style: single
> ```
> 
> Let me know if I am doing something wrong

@pawelpasterz  you must run on physical device

**Comment by pawelpasterz** [comment]
> > I followed the test plan but can't find any `performanceMetrics.json`
> > Here is my config
> > ```
> > gcloud:
> >   app: ~/app-debug.apk
> >   test: ~/app-single-success-debug-androidTest.apk
> > flank:
> >     num-test-runs: 3
> >     output-style: single
> > ```
> > 
> > 
> > Let me know if I am doing something wrong
> 
> @pawelpasterz you must run on physical device. I have updated test plan

Thanks!

**Review by pawelpasterz — DISMISSED** [review]
We have the option `disable-results-upload`. If set true we should not upload any results to the bucket. But I can see `performanceMetrics.json` are uploaded anyway
Screenshot 2020-11-18 at 15 04 16
With `disable-results-upload` set to false output is rather ugly 
Screenshot 2020-11-18 at 15 12 47
I see some items we need to decide/discuss/fix
1. Are `performanceMetrics.json` considered to be 'the same' results as the rest of flank's results?
1. Let's align/beautify the output
1. Let's decide what we want to print actually. Currently, we just print the message `Uploading [file name]` do we want to stick with that? Or we can print a gcs link but on a matrix level? So every matrix will have it's own. IMO we should decide on one convention and not mix them

Of course, I can be wrong. I'd like to get your opinion.

cc
@bootstraponline @jan-gogo

**Comment by piotradamczyk5** [comment]
> We have the option `disable-results-upload`. If set true we should not upload any results to the bucket. But I can see `performanceMetrics.json` are uploaded anyway
> Screenshot 2020-11-18 at 15 04 16
> With `disable-results-upload` set to false output is rather ugly
> Screenshot 2020-11-18 at 15 12 47
> I see some items we need to decide/discuss/fix
> 
> 1. Are `performanceMetrics.json` considered to be 'the same' results as the rest of flank's results?
> 2. Let's align/beautify the output
> 3. Let's decide what we want to print actually. Currently, we just print the message `Uploading [file name]` do we want to stick with that? Or we can print a gcs link but on a matrix level? So every matrix will have it's own. IMO we should decide on one convention and not mix them
> 
> Of course, I can be wrong. I'd like to get your opinion.
> 
> cc
> @bootstraponline @jan-gogo

I will add the flag to disable uploading if `disable-results-upload` present
In the case of output, I agreed that I should not add a confirmation message (with the link), because it brokes our convention, I will delete it. 
I will create the task to research and think about good output printing for uploading files

**Comment by adamfilipow92** [comment]
- [X] Tested without ```disable-results-upload``` works and output looks good
- [X] Tested with ```disable-results-upload``` works as expected

**Review by adamfilipow92 — APPROVED** [review]
Tested and works! 👍

**Pull request merged**
